#!/bin/bash
docker stop tomcatdemostr
docker rm tomcatdemostr
newIpAdd=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' mysqldemo)
oldIpAdd=$(grep sed run_script |cut -d "/" -f 3)
echo $newIpAdd $oldIpAdd
sed -i "s/${oldIpAdd}/${newIpAdd}/" run_script
docker build -t demo/tomcat .
docker run -it -p 8085:8080 --name tomcatdemostr demo/tomcat run_script
